settings:
  title: 'Status Page'
  url: 'https://status.pawb.social' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: furry.engineer # unique identifier
    name: furry.engineer
    description: 'Duct tape, hotfixes, and poor soldering!' # default=empty
    url: 'https://furry.engineer/api/v2/instance' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: pawb.fun
    name: pawb.fun
    description: 'Pawbs, beans, and all things fluffy'
    url: 'https://pawb.fun/api/v2/instance'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true
